### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by oushujun** [zhangrengang/LTR_classifier#1]
Hi @zhangrengang ,

Thanks for developing this great package! I am testing it now and found a typo in this test line:
`python ../LTR_classifier.py Classifier rice6.9.5.rexdb.liban.gff3 > rice6.9.5.liban.rexdb.gff3.anno`

where `rice6.9.5.rexdb.liban.gff3` should be `rice6.9.5.liban.rexdb.gff3`

Best,
Shujun

**Comment by zhangrengang** [comment]
Yes. I have revised it.
